dist: xenial
sudo: require

language: python
python: "3.7"

compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-8
            - g++-8
        update: true

install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
    - pip install conan
    - conan user

script:
    - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
    - gcc -v && g++ -v
    - mkdir build && cd build
    - conan install .. --build missing -s compiler.libcxx=libstdc++11
    - ~/.conan/data/cmake_installer/3.14.5/conan/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/cmake .. -DCMAKE_BUILD_TYPE=Debug
    - ~/.conan/data/cmake_installer/3.14.5/conan/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/cmake --build .
    - ./bin/tests
    - ../test/alltest.sh . ./bin/smam
