dist: xenial
sudo: require

language: cpp
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libcurl4-gnutls-dev
            - libxml++2.6-dev
            - gcc-6
            - g++-6
            - cmake
        update: true

install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
    - gcc -v && g++ -v && cmake --version
    - mkdir build && cd build && cmake .. && cmake --build . && ./bin/tests
