dist: xenial
sudo: require

language: cpp
compiler: gcc

before_install:
    - sudo apt-get install -y libcurl4-gnutls-dev

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-6
            - g++-6
            - cmake
        update: true

script:
    - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
    - gcc -v && g++ -v && cmake --version
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
    - ./bin/tests
